import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Header from '../components/Header'
import RestaurantList from '../components/RestaurantList'

import { SearchIcon } from '@heroicons/react/solid';

export default function Home() {
  const [query, updateQuery] = useState("");

  return (
    <div className="bg-gray-600">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="bg-gray-100 font-sans content p-6">
        <div className="p-8">
          <div className="bg-white flex items-center rounded-full shadow-xl">
            <input onChange={e => updateQuery(e.target.value.toLocaleLowerCase())}
              value={query} className="rounded-l-full w-full py-4 px-6 text-gray-700 leading-tight focus:outline-none" id="search" type="text" placeholder="Search" />
            <div className="p-4">
              <button className="text-white rounded-full p-2 hover:bg-blue-400 focus:outline-none w-12 h-12 flex items-center justify-center">
                <SearchIcon />
              </button>
            </div>
          </div>
        </div>
        <RestaurantList search={query} />
      </main>
    </div >
  )
}
