import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Header from '../components/Header'
import RestaurantList from '../components/RestaurantList'

export default function Home() {
  const [query, updateQuery] = useState("");

  return (
    <div className="bg-page-light">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="bg-gray-100 font-sans content p-6">
        <input type="text" onChange={e => updateQuery(e.target.value.toLocaleLowerCase())}
          value={query} />
        <RestaurantList search={query} />
      </main>
    </div>
  )
}
